import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { EdgeStoreProvider } from "@/lib/edgestore";
import QueryProvider from "@/components/providers/QueryProvider";
import { Toaster } from "sonner";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <EdgeStoreProvider>
        <body className="antialiased">
          <QueryProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <main className="mt-10">
                {children}
              </main>
              <Toaster />
            </ThemeProvider>
          </QueryProvider>
        </body>
      </EdgeStoreProvider>
    </html>
  );
}
